apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
  labels:
    app: ai-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          # image: ai-service:latest   # Replace with your actual image (e.g., yourname/ai-service:1.0)
          image: 723609007800.dkr.ecr.us-west-2.amazonaws.com/airbnb-images-2025:ai
          imagePullPolicy: Always
          ports:
            - containerPort: 7005

          env:
            # ---- Core Settings ----
            - name: PORT
              value: "7005"
            # ---- CORS Configuration ----
            - name: CORS_ORIGINS
              value: "http://localhost:3000,http://localhost:5173,http://127.0.0.1:5173,http://airbnb.local,https://airbnb.local"

            # ---- MongoDB Atlas ----
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-uri
            - name: MONGO_DB
              value: "airbnb_db"

            # ---- Tavily & OpenWeather ----
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: tavily
            - name: OPEN_WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: openweather

            # ---- Ollama phi3:mini ----
            - name: OLLAMA_BASE_URL
              value: "http://ollama:11434"
            - name: OLLAMA_MODEL
              value: "phi3:mini"
      restartPolicy: Always
