apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 7004          # service port
      targetPort: 7004    # container port
  type: ClusterIP         # internal communication (no external exposure)
f