apiVersion: v1
kind: Service
metadata:
  name: owner-service
  labels:
    app: owner-service
spec:
  selector:
    app: owner-service
  ports:
    - protocol: TCP
      port: 7003
      targetPort: 7003
  type: ClusterIP
