apiVersion: v1
kind: Service
metadata:
  name: property-service
  labels:
    app: property-service
spec:
  selector:
    app: property-service
  ports:
    - protocol: TCP
      port: 7002
      targetPort: 7002
  type: ClusterIP
