apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongo-uri: "mongodb+srv://mounashreeprasanna_db_user:bOkFaUsrl2QOFydr@cluster-236.njc5716.mongodb.net/airbnb_db?retryWrites=true&w=majority"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  traveler-secret: "password"
  booking-secret: "password"
  owner-secret: "password"
  property-secret: "password"
