# ---------- MongoDB Atlas ----------
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongo-uri: "mongodb+srv://mounashreeprasanna_db_user:bOkFaUsrl2QOFydr@cluster-236.njc5716.mongodb.net/airbnb_db?retryWrites=true&w=majority"
---
# ---------- JWT Secrets ----------
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  traveler-secret: "password"
  booking-secret: "password"
  owner-secret: "password"
  property-secret: "password"
---
# ---------- AI Service Secrets ----------
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
type: Opaque
stringData:
  tavily: "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"
  openweather: "f8aa83d8439715490b519989a5415fa7"
